### ISSUE TITLE
Worker not returning a response on the latest version of Detekt

### ISSUE THREAD

**Issue by Bencodes** [buildfoundation/bazel_rules_detekt#83]
Tested using Detekt 1.13.x and 1.14.x using release `bffa68b4948aa26153185f4feda278557dc01951`

```console
(18:28:38) ERROR: /build/instant-features/formbuilder/safety-net-action/BUILD:3:21: Detekt instant-features/formbuilder/safety-net-action/lib_detekt_detekt_report.txt failed: Worker process did not return a WorkResponse:
```

This is our toolchain setup

```python
load("@rules_detekt//detekt:toolchains.bzl", "rules_detekt_toolchains")

rules_detekt_toolchains(detekt_version = "1.13.1")
```

**Comment by Bencodes** [comment]
Getting this error after updating bazel_rules_detekt to 1.14.0:

```
There was 1 failure:
1) it returns failure result on Detekt failed execution(io.buildfoundation.bazel.detekt.execute.DetektExecutableTests)
java.lang.NoSuchMethodError: java.io.ByteArrayOutputStream.toString(Ljava/nio/charset/Charset;)Ljava/lang/String;
        at io.buildfoundation.bazel.detekt.execute.Executable$DetektImpl$execute$1.invoke(Executable.kt:31)
        at io.buildfoundation.bazel.detekt.execute.Executable$DetektImpl$execute$1.invoke(Executable.kt:11)
        at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:58)
        at kotlin.collections.ArraysKt___ArraysKt.joinTo(_Arrays.kt:13752)
        at kotlin.collections.ArraysKt___ArraysKt.joinToString(_Arrays.kt:13969)
        at kotlin.collections.ArraysKt___ArraysKt.joinToString$default(_Arrays.kt:13968)
        at io.buildfoundation.bazel.detekt.execute.Executable$DetektImpl.execute(Executable.kt:30)
        at io.buildfoundation.bazel.detekt.execute.DetektExecutableTests.it returns failure result on Detekt failed execution(DetektExecutableTests.kt:21)

FAILURES!!!
Tests run: 7,  Failures: 1
```

**Comment by arturdryomov** [comment]
OK, so we are in all sorts of trouble.

* Detect changed the API for CLI and introduced another one for tooling. It’s manageable.
* Detect [migrated to Kotlin 1.4 in 1.12.0](https://github.com/detekt/detekt/releases/tag/v1.12.0). However, `rules_kotlin` [does not support it, even via custom toolchain](https://github.com/bazelbuild/rules_kotlin/pull/363). The lack of 1.4 means that the runtime is screwed (`NoSuchMethodError` in the stacktrace below).

<details>
  <summary>Stacktrace with Detekt 1.14.1 and changed API</summary>
  
```
	at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:42)
	at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.measure(Lifecycle.kt:30)
	at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze(Lifecycle.kt:36)
	at io.gitlab.arturbosch.detekt.core.tooling.DefaultLifecycle.analyze(Lifecycle.kt:57)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:43)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:21)
	at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:24)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:42)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:25)
	at io.gitlab.arturbosch.detekt.cli.runners.Runner.call(Runner.kt:33)
	at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:23)
	at io.buildfoundation.bazel.detekt.execute.Detekt$Impl.execute(Detekt.kt:14)
	at io.buildfoundation.bazel.detekt.execute.Executable$DetektImpl.execute(Executable.kt:21)
	at io.buildfoundation.bazel.detekt.execute.WorkerExecutable$Impl.execute(WorkerExecutable.kt:13)
	at io.buildfoundation.bazel.detekt.Application$Worker$run$1.apply(Application.kt:40)
	at io.buildfoundation.bazel.detekt.Application$Worker$run$1.apply(Application.kt:31)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:550)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:478)
	at io.buildfoundation.bazel.detekt.stream.WorkerStreams$Impl$requestSource$1.invoke(WorkerStreams.kt:24)
	at io.buildfoundation.bazel.detekt.stream.WorkerStreams$Impl$requestSource$1.invoke(WorkerStreams.kt:15)
	at io.buildfoundation.bazel.detekt.stream.WorkerStreams$sam$io_reactivex_rxjava3_core_FlowableOnSubscribe$0.subscribe(WorkerStreams.kt)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15750)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15696)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(java.lang.Class, java.lang.String, java.lang.String, int)'
	at io.gitlab.arturbosch.detekt.cli.DetektProgressListener.<clinit>(DetektProgressListener.kt)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 41 more
```
</details>

Overall this means that Detekt 1.14.1 is unsupported until `rules_kotlin` catches up.

**Comment by arturdryomov** [comment]
@Bencodes, @artem-zinnatullin, since `rules_kotlin` is pretty much dead (again) I rewrote our wrapper in Java and removed Kotlin from the codebase. It’s a local change for now. As a result, Detekt 1.14.2 runs fine without runtime issues. Do you think it’s a good idea or a bad idea? It kind of sucks of course but it works and has less dependencies.

**Comment by Bencodes** [comment]
It's obviously not ideal but I think it's fine given the fact that these are Bazel rules and the underlying language doesn't really alter how people use these rules.

**Comment by Bencodes** [comment]
Kotlin 1.4 just got merged into the upstream rules_kotlin repo

**Comment by Kernald** [comment]
From cgruber on Slack, the rules should have a release within one or two days.

**Comment by Bencodes** [comment]
The rules just got released https://github.com/bazelbuild/rules_kotlin/releases/tag/v1.5.0-alpha-1

**Comment by arturdryomov** [comment]
@Bencodes, is the issue present with latest changes?

**Comment by arturdryomov** [comment]
Gonna close this for now and push a new version tag after some testing. Feel free to reopen @Bencodes.
